version: '3.9'

services:
  mssql:
    container_name: mssql_container_m1
    image: mcr.microsoft.com/azure-sql-edge:1.0.7
    user: root
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
    environment:
      - ACCEPT_EULA=Y
      #set password for SA user
      - SA_PASSWORD=mssql1Ipw
      - MSSQL_PID=Developer