version: '3.9'
 
services:
    gogs:
        image: gitea/gitea:latest
        container_name: gitea_container
        ports:
            - "127.0.0.1:3000:3000"
            - "127.0.0.1:2221:22"
        volumes:
            - ./data:/data
            - ./bak:/backup
        environment:
            - TZ="Europe/London"
            - RUN_CROND="true"
            - BACKUP_INTERVAL="5m"
            - BACKUP_RETENTION="5m"
        restart: unless-stopped
        networks:
            - gitea
        logging:
            # keep 3 log files, maximum size of 10m (default is unlimited)
            options:
                max-size: "10m"
                max-file: "3"
networks:
    gitea:
        driver: bridge