version: '3.9'

services:
  mssql:
    container_name: mssql_container
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
      - MSSQL_PID=Developer