version: "3.9"
services:
  snapdrop:
    image: redis/redis-stack:latest
    container_name: redis_container
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
      - 8001:8001
    restart: unless-stopped